Pacman get valid moves
cmsc389T-spring23/Team9 pull request #9
Opened 2023-02-24 18:41 UTC by BraydenNgo

2023-03-01 17:25 UTC, rohitsengupta1 requested changes
Check the comments I made otherwise looks good, but just want to check a few things before approving

2023-03-01 17:25 UTC, rohitsengupta1 commented on Projects/P2/app/src/main/java/pacman/PacMan.java
> -    return null;
how come we are returning null at the beginning of the function should this be changed?

2023-03-01 17:25 UTC, rohitsengupta1 commented on Projects/P2/app/src/main/java/pacman/PacMan.java
> +      for(int j = 0; j < 2; j++){
is there a reason you are only iterating up to i = 2 and j = 2

2023-03-01 17:25 UTC, rohitsengupta1 commented on Projects/P2/app/src/main/java/pacman/PacMan.java
> +    return validMovesList;
otherwise looks good

2023-03-01 17:25 UTC, rohitsengupta1 commented on Projects/P2/app/src/test/java/pacman/TestPacManValidMoves.java
> +    NoFrame frame = new NoFrame();
Also looks good

2023-03-01 18:07 UTC, BraydenNgo commented on Projects/P2/app/src/main/java/pacman/PacMan.java
> -    return null;
this is what the file originally was before implementing (it was changed from returning null)

2023-03-01 23:32 UTC, BraydenNgo commented on Projects/P2/app/src/test/java/pacman/TestPacManValidMoves.java
> +    NoFrame frame = new NoFrame();
see new changes to commit

2023-03-02 03:51 UTC, rohitsengupta1 approved these changes

2023-03-02 03:52 UTC, rohitsengupta1 approved these changes

2023-03-15 19:55 UTC, merged